---
title: "KATES-PAGES"
date: 2019-04-07
---

title: Kate's werds
author: maccbird
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Super excited you're here.  Let's get started!

# social links
twitter_username: your-twitter-handle
github_username:  maccbird

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
